### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by rattrayalex** [rudi23/yup-to-openapi#1]
Hi there,

This looks like an awesome project! The test file is pretty promising in terms of feature-completeness. 

Would you be willing to write, or accept a PR for, documentation enumerating the features which are supported and how they work?

I am sure that not 100% of openapi specs can be generated with this tool, and not 100% of yup validators will work; maybe a list of what does work, [like this](https://github.com/touchifyapp/spec2ts/blob/master/packages/jsonschema/README.md#implementations), could help?

Thanks!

**Comment by rudi23** [comment]
I hope a new documentation will help you, I'm sorry for such a delay 😞

**Comment by rattrayalex** [comment]
Yes, very nice! looks great! thank you!
